MATHEMATICS

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])

In [5]:
a

array([1, 2, 3, 4])

In [3]:
a * 2

array([2, 4, 6, 8])

In [6]:
a + 2

array([3, 4, 5, 6])

In [7]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [8]:
a ^ 2

array([3, 0, 1, 6], dtype=int32)

In [9]:
b = np.array([1,0,1,0])

In [10]:
a + b

array([2, 2, 4, 4])

In [11]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [12]:
# Take the trigonometry values of all
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [13]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [14]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [15]:
np.cosh(a)

array([ 1.54308063,  3.76219569, 10.067662  , 27.30823284])

LINEAR ALGEBRA

In [4]:
c = np.ones((2,3), dtype='int32')
c

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
d = np.full((3, 2), 2) #setting the value to 2
print(c)
print(d)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [6]:
#Algebra function multiplies the matrix
np.matmul(c,d)

array([[6, 6],
       [6, 6]])

In [11]:
#Finding the determinant

e = np.identity(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
np.linalg.det(e)

1.0

In [13]:
f = np.array([[1, 2, 3], [4, 5, 6], [2, 4, 6]])
np.linalg.det(f)

0.0