In [1]:
import numpy as np

LOADING DATA FROM A FILE

In [2]:
#NB : delimiter is known as a seperator

In [4]:
#getting the file using np.genfromtxt
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32') #Sets it to int32

array([[ 1,  2,  4,  5,  6,  3,  4,  7,  8,  0,  7,  6,  5,  8,  9,  2,
         1,  3],
       [ 6,  4,  6,  7,  3,  2,  1,  4,  3,  2,  4,  5,  5,  6,  7,  6,
         4,  0],
       [ 0,  9,  8,  7,  6,  5,  4,  3, 55,  5,  6,  7,  9,  8,  7,  5,
         4,  3]])

Boolean masking and advance indexing

In [5]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False]])

In [7]:
#Getting the values that are greater than 50
filedata[filedata > 50]

array([55.])

In [8]:
# You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
#Get 2,3,9
a[[1,2,8]]

array([2, 3, 9])

In [10]:
print(filedata)

[[ 1.  2.  4.  5.  6.  3.  4.  7.  8.  0.  7.  6.  5.  8.  9.  2.  1.  3.]
 [ 6.  4.  6.  7.  3.  2.  1.  4.  3.  2.  4.  5.  5.  6.  7.  6.  4.  0.]
 [ 0.  9.  8.  7.  6.  5.  4.  3. 55.  5.  6.  7.  9.  8.  7.  5.  4.  3.]]


In [11]:
#Tells if any of the values in each column is greater than 50
np.any(filedata > 50, axis=0)

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False])

In [12]:
#Tells if all of the values in each column is greater than 50
np.all(filedata > 50, axis= 0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [13]:
#Adding and 
((filedata > 8) & (filedata < 10))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False]])

In [14]:
# Reserve of command above(NOT operator)
(~((filedata > 8) & (filedata < 10)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True]])