STATISTICS

In [2]:
import numpy as np

In [3]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
print(stats)

[[1 2 3]
 [4 5 6]]


In [8]:
#Taking the minimum value
np.min(stats)

1

In [11]:
#Giving the min of the first and second row
np.min(stats, axis=1)

array([1, 4])

In [12]:
#Giving the values of the first row because they are all the minimum values
np.min(stats, axis=0)

array([1, 2, 3])

In [7]:
#Taking the maximum value
np.max(stats)

6

In [14]:
 #Summing up allthe elements in the matrix
np.sum(stats)

21

In [15]:
#Summing up the values of the colums
np.sum(stats, axis=0)

array([5, 7, 9])